### ISSUE TITLE
Model deeplabv3-plus-human-parsing-resnet-50-backbone.h5

### ISSUE THREAD

**Issue by dnalexen** [lattice-ai/DeepLabV3-Plus#5]
Hello, can you share the file deeplabv3-plus-human-parsing-resnet-50-backbone.h5 for those who do not have access to a GPU for a long time to train the model?

**Comment by soumik12345** [comment]
Hi @dnalexen , apologies for the delay in response. We would be publishing the pre-trained models for all our projects as part of our official release which is scheduled for February 2021.

**Comment by NyanSwanAung** [comment]
hey @dnalexen , if you're using google colab with supported GPU, you can train the model with `batch_size=7 `for both train and validation dataset. You can simply change it in their awesome config file. However, if you train with default `batch_size=8`, colab will crash due to Out of Memory Allocation(OOM). Cheers! Shout out to lattice-ai team for providing us this phenomenon open-source code 💯⭐️

**Comment by dhuynguyen94** [comment]
> hey @dnalexen , if you're using google colab with supported GPU, you can train the model with `batch_size=7 `for both train and validation dataset. You can simply change it in their awesome config file. However, if you train with default `batch_size=8`, colab will crash due to Out of Memory Allocation(OOM). Shout out to lattice-ai team for providing us this phenomenon open-source code 💯⭐️ Cheers!

Hi. I tried to run on Google Colab with batchsize is 7. However, there is a error named "TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.". Did you meet this error before? Thank you so much!

**Comment by NyanSwanAung** [comment]
@dhuynguyen94 No I didn't,  how did you download the dataset? Share me your script.

**Comment by Sesamestrong** [comment]
> > hey @dnalexen , if you're using google colab with supported GPU, you can train the model with `batch_size=7 `for both train and validation dataset. You can simply change it in their awesome config file. However, if you train with default `batch_size=8`, colab will crash due to Out of Memory Allocation(OOM). Shout out to lattice-ai team for providing us this phenomenon open-source code 💯⭐️ Cheers!
> 
> Hi. I tried to run on Google Colab with batchsize is 7. However, there is a error named "TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.". Did you meet this error before? Thank you so much!

The source of the problem is an error with how CamVid is loaded.
I fixed it by running
```sh
bash dataset/camvid.sh
mv camvid/ dataset/camvid
```
This fixes the problem because the config file looks for images in `dataset/camvid`, not `./camvid`.

**Comment by EMHussain** [comment]
> Hi @dnalexen , apologies for the delay in response. We would be publishing the pre-trained models for all our projects as part of our official release which is scheduled for February 2021.

Any update on pre-trained model?

**Comment by apolo74** [comment]
Same question again, could you guys share your pre-trained weights, please?
deeplabv3-plus-human-parsing-resnet-50-backbone.h5
Thanks in advance,
Boris
